export const movieDbConstants = {
    GETSHOWS_REQUEST: 'GET_SHOWS_REQUEST',
    GETSHOWS_SUCCESS: 'GET_SHOWS_SUCCESS',
    GETSHOWS_FAILURE: 'GET_SHOWS_FAILURE',

    GETSHOW_REQUEST: 'GET_SHOW_REQUEST',
    GETSHOW_SUCCESS: 'GET_SHOW_SUCCESS',
    GETSHOW_FAILURE: 'GET_SHOW_FAILURE',

    GETMOVIES_REQUEST: 'GET_MOVIES_REQUEST',
    GETMOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
    GETMOVIES_FAILURE: 'GET_MOVIES_FAILURE',

    GETMOVIE_REQUEST: 'GET_MOVIE_REQUEST',
    GETMOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
    GETMOVIE_FAILURE: 'GET_MOVIE_FAILURE',
};