export const movieDbConstants = {
    GETSHOWS_REQUEST: 'GET_SHOWS_REQUEST',
    GETSHOWS_SUCCESS: 'GET_SHOWS_SUCCESS',
    GETSHOWS_FAILURE: 'GET_SHOWS_FAILURE',

    GETMOVIES_REQUEST: 'GET_MOVIES_REQUEST',
    GETMOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
    GETMOVIES_FAILURE: 'GET_MOVIES_FAILURE',
};